### ISSUE TITLE
issue with casting to dense 

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#82]
I try to use the new casting function but got this error ?

![image](https://user-images.githubusercontent.com/1186658/191016535-f5ab3c52-889b-4e3e-a126-8f2e9b49bcd7.png)

![image](https://user-images.githubusercontent.com/1186658/191016563-c7f3de42-5463-4dd0-baba-7e1aebbbd45e.png)

**Comment by PatReis** [comment]
Oh, yes, must be `tf.ones_like()`, sorry. I pushed changes. Didn't have time yet to check your code, sorry.

**Comment by thegodone** [comment]
yes we progress, after this it will be my code to check ;-)
new issue now on the EdgeIndicesToDense
![image](https://user-images.githubusercontent.com/1186658/191056590-17bf1a31-d585-4db6-8f4f-629c0ce2372a.png)

![image](https://user-images.githubusercontent.com/1186658/191056822-ffac5b86-4909-450a-9c6a-e28e932a7e36.png)

**Comment by thegodone** [comment]
very close last error is on edge feature dim look like

![image](https://user-images.githubusercontent.com/1186658/191075336-873deac8-a761-48aa-b19b-3384ee046988.png)

![image](https://user-images.githubusercontent.com/1186658/191075425-5df9d537-3029-438c-b524-ea562151d482.png)

**Comment by thegodone** [comment]
I've tried your last commit yesterday night and still have an error. One small remark before to continue is this version R-MAT is easier to implement (ie ragged compatible) ? https://arxiv.org/abs/2110.05841
If yes than I think we should do this one that looks better than the MAT anyway. 

Status this morning: 

![image](https://user-images.githubusercontent.com/1186658/191180687-bb2f54c1-16b7-40f6-8449-4f7e714bc5ed.png)


The issue looks to be the DynamicRaggedShape that cannot be converted to int32 for shape, if I remove it just to see what happends, I have a second issue related to cpu/gpu issue to handle int64 indices with scatter_nd so, the progress is like in jungle...

![image](https://user-images.githubusercontent.com/1186658/191180786-8d182e33-f836-4343-ad2e-416b791926ab.png)

last code I use to get the second error
<img width="950" alt="image" src="https://user-images.githubusercontent.com/1186658/191180595-8afd368d-49ef-4ef4-b474-cf9e17c2c417.png">

My issue is that I need compatible cpu arm64 code.

**Comment by PatReis** [comment]
Hm, sorry, I test the layer in graph mode. I uploaded the bug-fix. should work now. But I will check later this afternoon.

**Comment by thegodone** [comment]
Hum are you sure it's fix ? I still have a problem. I am using tf 2.10 now I just update yesterday from 2.9  

![image](https://user-images.githubusercontent.com/1186658/191216785-eb51d630-19a5-486f-91ee-7b3f096b865f.png)

**Comment by PatReis** [comment]
Not really, I will test it in the afternoon. The problem is to get the proper shape in graph mode. I adjusted it now. Should be better working now.

**Comment by PatReis** [comment]
Okay, I also had the wrong embedding layer applied. I also updated MAT.py

**Comment by thegodone** [comment]
Look much better yes. Now I see my mistakes time for bug fix on my side.

Le mar. 20 sept. 2022 à 12:19, Patrick Reiser ***@***.***> a
écrit :

**Comment by thegodone** [comment]
Ok i fix my bugs now, But Lucidbrains MAT code is only compatible with Adj  "1-Dim" (aka not edge features). 

![image](https://user-images.githubusercontent.com/1186658/191242940-98fb19bf-1a46-42b6-b851-e4d0180f48ee.png)

**Comment by thegodone** [comment]
Yes so by default it's adj connectivity not adj including edge_features (there is an option in the original MAT code to set it to true).

![image](https://user-images.githubusercontent.com/1186658/191250673-40ee93bf-4d0b-42b9-bfaf-3b189b38b163.png)


Can you add this option to run a switch case option to get adj connectivity or adj features (current code) ?

**Comment by thegodone** [comment]
I find the reference code for the 2021 version https://github.com/gmum/huggingmolecules/blob/main/src/huggingmolecules/models/models_rmat.py

**Comment by thegodone** [comment]
I cannot find a way to have the non edge features adj matrice ?

![image](https://user-images.githubusercontent.com/1186658/191315580-18812453-4f54-4e55-ae4e-99a379c08a80.png)

![image](https://user-images.githubusercontent.com/1186658/191315325-e5ba1cf3-0d99-43db-b461-dac4e27dde39.png)

**Comment by thegodone** [comment]
this is a second issue. Code now compile but the dimension of the distance matrix must be also the same as the adjacency matrix

![image](https://user-images.githubusercontent.com/1186658/191427467-bc4d1b26-ebff-47d9-a32a-749eb55f5f16.png)

I will make a pull request on my code now but the fact that we must have true distance matrix pad and trux adjacency matrix pad is important for making the code running. 

I will add the masks for softmax and distance soon

**Comment by thegodone** [comment]
close to the end

with my last PR I have this error related to layerNorm broadcast dim (i guess ragged side effect) 
![image](https://user-images.githubusercontent.com/1186658/191525125-0af63b29-631e-415f-aa0e-184ce31b3090.png)

**Comment by thegodone** [comment]
I try lost code tonight and I see a strange issue in the first iteration the n has 2 None dim shapes
![image](https://user-images.githubusercontent.com/1186658/191610916-54fe10ac-659a-4c52-a2a6-7b271231e4c1.png)

this is causing a bug during training
